### ISSUE TITLE
Giving Wrong Spelling 

### ISSUE THREAD

**Issue by thegenuinegourav** [BuildmLearn/BuildmLearn-Toolkit-Android#101]
Example: Writing Apple with autocorrect options gives wrong spelling in spelling template!
Screenshots from the app can explain this situation
![screenshot_2016-03-04-21-29-43](https://cloud.githubusercontent.com/assets/16540657/13533467/97ec182a-e256-11e5-8c61-b25f3b4fcee7.png)
![screenshot_2016-03-04-21-30-03](https://cloud.githubusercontent.com/assets/16540657/13533473/9d567c24-e256-11e5-979b-295021742376.png)
![screenshot_2016-03-04-21-30-10](https://cloud.githubusercontent.com/assets/16540657/13533478/a1e03b54-e256-11e5-901e-cf5a0749cf05.png)

**Comment by championswimmer** [comment]
Still having this issue with the first word

**Comment by gourav96suri** [comment]
Can you elaborate first word issue

**Comment by championswimmer** [comment]
@gourav96suri 
In an app I build, the very first word always is wrong. The 2nd and onwards work correctly

**Comment by parthuest** [comment]
in my phone I cant see the spell suggestions while I enter spelling

**Comment by gourav96suri** [comment]
Doesn't your android phone provides autocorrect option?

**Comment by parthuest** [comment]
it obviously provides auto-correct options in all other apps..but not in simulator of buildmlearn

**Comment by gourav96suri** [comment]
![screenshot_2016-03-22-10-17-33](https://cloud.githubusercontent.com/assets/16540657/13942347/7fe3c1e6-f017-11e5-993e-ec8a0099f82f.png)
It is providing in my phone!
By the way, Which branch are you using: master or bug fixes or default playstore app??

**Comment by parthuest** [comment]
master

**Comment by parthuest** [comment]
should I use bug fixes?

**Comment by parthuest** [comment]
https://plus.google.com/u/0/photos/albums/pa2cmjqhperjbur9aeek5ft3n75aa4q67?pid=6264740715104419906&oid=112530882331276428914

**Comment by parthuest** [comment]
![2016-03-21](https://cloud.githubusercontent.com/assets/17997228/13942718/77f6fc10-f01b-11e5-964e-125a01e31f1b.png)

**Comment by scopeInfinity** [comment]
@parthuest `bug-fixes` branch is current ahead of `master`
And for _Words Suggestions_ , suggestions are actually meant to hidden and are not visible even in my phone.
@gourav96suri Can you check why suggestions are visible in your phone or how are you planning to fix it.

**Comment by gourav96suri** [comment]
@scopeInfinity I have fixed the problem in my new branch!
Link to that :+1: 
https://github.com/gourav96suri/BuildmLearn-Toolkit-Android/commit/e65b0f02c80602cc3ed3d3fb9e04651894c38da4

**Comment by scopeInfinity** [comment]
@gourav96suri It seems you are using trim for the fix.

Is _Words Suggestions_ still showing in your phone?

**Comment by gourav96suri** [comment]
Yess it is!!

**Comment by scopeInfinity** [comment]
@gourav96suri Any idea for the cause of this problem?
I guess this issue can be fixed using _trim_ as you have implemented, and this new problem is likely to come under a new issue.

**Comment by opticod** [comment]
I tried duplicating the situation in different API real-devices, but was unable to duplicate the ```word suggestions```. 
I even checked the code, it seems fine to me.

Probable cause: 
```android:inputType``` is found not to work normally in HTC Desire 2.2 . There may be few more unknown devices. 

Can you share your testing SDK version and device model?

**Comment by gourav96suri** [comment]
@opticod
SDK Version :23
Device : Samsung Note3 Neo, Samsung Grand Quatro (Both gives the word suggestion!
This problem is solved using trim() method! See the link above that I have shared

**Comment by opticod** [comment]
Closed via  1f80476
